# cluster test
include: 'rules/cluster_test.smk'

# QC
include: 'rules/QC.smk'

# Genome-guided alignment, assembly and read counting
include: 'rules/genome_guided.smk'

# Reference-free assembly and annotations
include: 'rules/repeatmasker.smk'
include: 'rules/soap_maker_all.smk'
include: 'rules/trinity_maker_all.smk'
include: 'rules/maker_noest.smk'
include: 'rules/decontamination.smk'
